# crie um pipeline no GitHub Actions para fazer o build de uma aplicação .Net 6
name: Pipeline

on:
  workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.x
        
        - name: Install dependencies
          run: dotnet restore
        
        - name: Build
          run: dotnet build --no-restore
        
        - name: Test
          run: dotnet test --no-restore --verbosity normal
        
        - name: Publish
          run: dotnet publish --no-restore --output ./publish

# faça um upload da pasta ./publish
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: app
            path: ./publish

# inclua um upload para a pasta ./terraform
        - name: Upload Terraform
          uses: actions/upload-artifact@v2
          with:
            name: terraform
            path: ./terraform


# crie um Job que faça o Deploy do terraform no Azure
# precisa baixar o artefato chamado terraform

    deploy:
        runs-on: ubuntu-latest
        environment:
          name: dev
          url: ${{ steps.deploy.outputs.webapp-url }}
        needs: build
        steps:
        - name: Download Terraform
          uses: actions/download-artifact@v2
          with:
            name: terraform
            path: ./terraform
         

# inclua o login no Azure
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}


# inclua o deploy do script azure bicep que está em ./terraform/deploy.bicep
        - name: Deploy Bicep
          run: az deployment group create --resource-group ${{ vars.APP_RG_NAME }} --template-file ./deploy.bicep --parameters appName=demoapp99${{ vars.APP_NAME }} --parameters location=${{ vars.APP_LOCATION }}
          working-directory: ./terraform


# baixe o artefato app
        - name: Download Artifact
          uses: actions/download-artifact@v2
          with:
            name: app
            path: ./app

# faça o deploy da pasta ./app no azure app service
        - name: Azure WebApp Deploy
          id: deploy
          uses: azure/webapps-deploy@v2
          with:
            app-name: demoapp99${{ vars.APP_NAME }}
            package: ./app


